# Site settings
title: Middleware Insight
email: your-email@domain.com
baseurl: /freelancer-theme/
url: https://unicolet.github.io/freelancer-theme
description: "Middleware Insight is a tool to expose middleware internals (messages, stats, logs) to the ELK stack for visualization, analysis and monitoring"
skills: "apache camel elk"
meta_author: Umberto Nicoletti

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Prometeo S.R.L.
  location: Crafted with love in Venice, Italy

# Postal address (add as many lines as necessary)
address:
  - Via Galilei 2/c/3
  - 30035, Mirano (VE) Italy

# Build settings
markdown: kramdown
permalink: pretty

# various configs
root_password: s3rvice